FROM golang:1.22 AS builder
WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o server_bin .

FROM scratch
COPY --from=builder /build/server_bin /server_bin
CMD ["/server_bin"]
