server {
    listen 80;
    server_name _;

    access_log /var/log/nginx/mywebapp_access.log;
    error_log /var/log/nginx/mywebapp_error.log;

    location = / { proxy_pass http://web:5000; }
    location /notes { proxy_pass http://web:5000; }

    location /health { return 404; }
    location / { return 404; }
}