FROM python:3.13-bookworm

WORKDIR /application

COPY . .

RUN pip install --no-cache-dir -r requirements_pinned.txt

EXPOSE 8080

CMD ["uvicorn", "spaceship.app:app", "--host", "0.0.0.0", "--port", "8080"]
