name: CI Pipeline

on:
  push:
    branches: ['main']
    tags: ['*']
  pull_request:
    branches: ['main']

jobs:
  linting:
    name: Run Linters
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python Linters
        run: pip install flake8 mypy yamllint

      - name: Run Flake8
        run: flake8 LAB1/app/app.py LAB1/app/migrate.py LAB1/tests/test_app.py --max-line-length=120

      - name: Run MyPy
        run: mypy LAB1/app/app.py LAB1/app/migrate.py --ignore-missing-imports

      - name: Run Yamllint
        run: yamllint LAB1/docker-compose.yml

      - name: Run Shellcheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './LAB1/app'

      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: LAB1/app/dockerfile
          ignore: DL3008
